CREATE TABLE example (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    quantity INTEGER NOT NULL DEFAULT 0
        CHECK (quantity >= 0),
    price NUMERIC(12, 2) NOT NULL DEFAULT 0
        CHECK (price >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    registration_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);