@startuml notificaciones-05-hld-secuencia
skinparam backgroundColor #FFFFFF
skinparam shadowing false
skinparam sequenceMessageAlign center
skinparam sequence {
    ArrowColor #1168BD
    LifeLineBorderColor #1168BD
    ParticipantBorderColor #003865
    ParticipantBackgroundColor #003865
    ParticipantFontColor #FFFFFF
    ActorBorderColor #003865
}

title HLD simple - Flujo de notificaciones

actor "Servicio interno\n(autenticado previamente)" as emisor
participant "API REST" as api
database "PostgreSQL" as db
queue "Redis" as redis
participant "Worker de envíos" as worker
participant "Proveedor genérico\nde email/SMS" as proveedor

== Solicitud ==
emisor -> api : POST /api/v1/notifications
api -> api : validar datos, plantilla y variables

alt solicitud inválida
    api --> emisor : 400 o 404
else solicitud válida
    api -> db : guardar notificación ENCOLADA
    api -> redis : encolar notificación
    api --> emisor : 202 Accepted
end

== Entrega asíncrona ==
redis -> worker : notificacionId
worker -> db : obtener notificación y plantilla
worker -> worker : controlar duplicados, throughput y renderizado
worker -> proveedor : enviar mediante librería 
proveedor --> worker : éxito o fallo

alt envío exitoso
    worker -> db : registrar intento y estado ENVIADA
else fallo reintentable
    worker -> db : registrar intento fallido
    worker -> redis : programar reintento con backoff
else fallo terminal
    worker -> db : registrar intento y estado FALLIDA
end

== Consulta o reintento manual ==
emisor -> api : GET estado/historial o POST /{id}/retry
api -> db : consultar estado e intentos
api -> redis : programar reintento si corresponde
api --> emisor : 200, 202, 400, 404 o 409



== Consulta o reintento manual ==
emisor -> api : POST, GET, PUT, DELETE /api/v1/platilla
api -> api : validar valores validos

    alt solicitud inválida
        api --> emisor : 400 o 404 datos no permitidos
    else solicitud válida
        api -> db : guardar, edita, elimina o deveulve plantilla
        api --> emisor : 202 
    end

@enduml
