@startuml notificaciones-02-bp-gestion-plantillas
title BP - Gestión de plantillas
start
:POST /templates o PUT/DELETE /templates/{id};
if (¿Contrato válido?) then (sí)
  if (¿DELETE?) then (sí)
    :Borrado lógico deleted_at;
    :204 o 404;
  else (no)
    :Validar placeholders == variables[];
    if (¿Nombre/canal activo duplicado?) then (sí)
      :409 Conflict;
    else (no)
      :Persistir creación o reemplazo;
      :201 o 200;
    endif
  endif
else (no)
  :400 Bad Request;
endif
stop
@enduml
